# Use Node image for React
FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . ./

# Build React app
RUN npm run build

# Serve using serve
RUN npm install -g serve

EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]
